### ISSUE TITLE
Lien mort (was: Il est mort, Jim)

### ISSUE THREAD

**Issue by emersion** [guyzmo/facturation_latex#1]
http://i.got.nothing.to/post/factures-en-LaTeX

**Comment by guyzmo** [comment]
ah, thanks, la bonne URL est: 
- http://i.got.nothing.to/hack/on/gestion-des-factures-en-autoentrepreneur/

je corrigerai ça, merci ☺

**Comment by guyzmo** [comment]
hop, done!
